
font_family BlexMono Nerd Font Mono
font_size 12

term xterm-256color

cursor_shape block

url_style curly

adjust_line_height 100%
adjust_column_width 100%
remember_window_size no
initial_window_width 830
initial_window_height 500
window_padding_width 10
cursor_blink_interval 1
hide_window_decorations yes
background_opacity	      0.80
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0

include ./theme.conf

