gui:
  border: rounded

  theme:
    activeBorderColor: ["#d3869b"]
    inactiveBorderColor: ["#665c54"]

    selectedLineBgColor: ["#3c3836"]

    optionsTextColor: ["#83a598"]

    unstagedChangesColor: ["#fb4934"]

    defaultFgColor: ["#ebdbb2"]

    cherryPickedCommitFgColor: ["#83a598"]
    cherryPickedCommitBgColor: ["#282828"]
